server.port: 8040
spring.application.name: user-service
eureka:
  registration.enabled: false
  client.serviceUrl.default: http://localhost:8761/eureka/v2
management.endpoints.web.exposure.include: hystrix.stream